---
matrix:
  include:
    - language: python
      python: '3.6'
      install:
        - pip install -e .[cli,tests,docs]
      script:
        - pytest --cov=rctclient --cov-report=term-missing ${@}
          # - pylint --mypy src/rctclient
          # - pytest --pylint src/rctclient
    - language: python
      python: '3.7'
      install:
        - pip install -e .[cli,tests,docs]
      script:
        - pytest --cov=rctclient --cov-report=term-missing ${@}
          # - pylint --mypy src/rctclient
          # - pytest --pylint src/rctclient
    - language: python
      python: '3.8'
      install:
        - pip install -e .[cli,tests,docs]
      script:
        - pytest --cov=rctclient --cov-report=term-missing ${@}
          # - oylint --mypy src/rctclient
          # - pytest --pylint src/rctclient
    - language: python
      python: '3.9'
      install:
        - pip install -e .[cli,tests,docs]
      script:
        - pytest --cov=rctclient --cov-report=term-missing ${@}
          # - oylint --mypy src/rctclient
          # - pytest --pylint src/rctclient
